bumps:

  - file: apps/cli/package.json
    json:
      - path: "version"
        semver: true

  - file: apps/web/package.json
    json:
      - path: "version"
        semver: true

  - file: apps/mobile/package.json
    json:
      - path: "version"
        semver: true

  - file: apps/mobile/src/lib/constants.ts
    regex:
      - pattern: "const version = '$VERSION'"
        semver: true
        count: 1
