name: Uplift

on:
  push:
    branches:
      - main

jobs:
  ci:
    timeout-minutes: 5
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Uplift
        uses: gembaadvantage/uplift-action@v2.0.1
        with:
          install-only: true

      - name: Tag & Release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_UPLIFT }}
        run: |
          echo GITHUB_TOKEN=$GITHUB_TOKEN
          uplift release
