name: Uplift

on:
  push:
    branches:
      - main

jobs:
  ci:
    timeout-minutes: 5
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Uplift
        uses: gembaadvantage/uplift-action@v2.0.1
        with:
          install-only: true
          args: none (this is a required field)

      - name: Tag & Release
        run: |
          uplift release --no-push

      - name: Push
        run: |
          git status
          git log
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GH_UPLIFT }}
